[package]
name = "bp3d-proto-dynamic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bp3d-protoc = { version = "1.0.0-rc.5.0.0", path = "../compiler", features = ["compiler", "api"] }
bp3d-proto = { version = "1.0.0-rc.5.0.0", path = "../runtime" }
bp3d-util = { version = "2.1.1", features = ["extension", "result"] }
bp3d-debug = "1.0.0-rc.6.2.0"
