[package]
name = "testprog"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bp3d-proto = { version = "1.0.0-rc.1.0.0", path = "../runtime" }

[build-dependencies]
bp3d-protoc = { version = "1.0.0-rc.1.0.0", path = "../compiler" }
