[package]
name = ""
path = "src"
#file-header = "path/to/file/header"

[options.unions]
union-set-discriminant = true


[options.import_ambiguous]
reads-messages = false
writes-messages = false
#disable-read = ["Name1", "Name2"]
#disable-write = ["Name1", "Name2"]

#[[dependency]]
#path = "/path/to/json.json5"
#package = "rust::crate::module::path"
