[package]
name = "bp3d-protoc"
version = "1.0.0-rc.1.0.0"
edition = "2021"
authors = ["Yuri Edward <yuri6037@outlook.com>"]
description = "BP3D protocol compiler/generator."
license = "BSD-3-Clause"
repository = "https://github.com/BlockProject3D/tools.proto"
readme = "../README.MD"
keywords = ["bp3d", "protoc"]
categories = ["network-programming", "development-tools::build-utils", "parsing"]

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
json5 = "0.4.1"
bp3d-util = { version = "1.0.0", features = ["simple-error", "path"] }
itertools = "0.13.0"
regex = "1.10.5"
