[package]
name = ""
path = "../testprog/src"

exclude = ["custom_codec"]

[options.unions]
union-set-discriminant = true
write-async = true

[options.enums]
write-async = true

[options.values]
write-async = true
